### ISSUE TITLE
CwlUtils.framework is missing in Products

### ISSUE THREAD

**Issue by andreyz** [mattgallagher/CwlSignal#26]
I'm including CwlSignal as a sub-project, which worked well before the xcode10 merge, since now I can't reference CwlUtils framework in the Copy to Frameworks build step.

**Comment by mattgallagher** [comment]
Hi @andreyz, I've replaced the "Aggregate" targets for building CwlUtils with hollowed out "Framework" targets (same approach used prior to the xcode10 branch) in commit 9ec066c7602d493c158f22ed3468e39359ba7f05. Please let me know if this helps – you should be able to add the CwlUtils.frameworks to link and copy phases as before.

I removed the Framework targets during the Xcode 10 betas because I was getting errors about multiple targets producing the CwlUtils.framework. I don't know if this was a bug fixed in later betas or if there was another cause – or if the problem might return – but the Framework targets are working for now.

**Comment by andreyz** [comment]
Thank you Matt! Commit 9ec066c solved it for me. Hope that didn't mess things up for everyone else :)
