### ISSUE TITLE
Release/Instruments build issues

### ISSUE THREAD

**Issue by monyschuk** [mattgallagher/CwlSignal#9]
I was preparing to do some leak tests on my code and noticed that Release/Instruments style builds weren't working. Pulled your latest and noticed that you'd changed an area that appeared to play a part, but it's not quite cleared up yet (I'm running Xcode 8.3beta):

```
/Users/mark/Developer/Analysis/Submodules/CwlSignal/.build/cwl_symlinks/CwlUtils/Sources/CwlUtils/CwlStackFrame.swift:44:35: error: use of unresolved identifier 'frame_address'
                let frame = StackFrame(address: frame_address())

```

Interestingly, if I remove the conditional OMIT_STACK_FRAME check then, while compile takes an inordinately long time, the build eventually succeeds and I'm able to run Instruments.app leaks.

**Comment by mattgallagher** [comment]
Oops, it looks like I pushed the CwlSignal changes but not the required updates to CwlUtils. I think I've set this conditional compilation up incorrectly – requiring cooperation between CwlSignal and CwlUtils. I've fixed it so that it's wholly implemented in CwlUtils so it can't fall out-of-sync like this again.

Fixes appear in CwlUtils 1.0.2 https://github.com/mattgallagher/CwlUtils/commit/059400f5fb1b1f4f8a25e26ee7156aa4b6574bdb

If, for some reason, the Swift Package Manager doesn't update CwlUtils when you build CwlSignal, remove the ".build" and "Packages" directories and try again.
